name: BackEnd Docker CICD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: false
  env_main: ${{secrets.ENV_main}}

defaults:
  run:
    working-directory: BackEnd

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    

    steps:
      - name: checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: create environment file
        run: |
          touch ./.env && echo "$env_main" >> ./.env

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push 
        uses: docker/build-push-action@v4
        if: github.event_name == 'push'
        with:
          context: ./BackEnd
          file: ./BackEnd/Dockerfile
          push: true
          tags: thespiritman/yantra-backend:main

      - name: Build Docker image
        if: github.event_name == 'pull_request'
        run: docker build -t myimage:${{ github.sha }} -f ./Dockerfile .